# *******************************************************************************
# Copyright (c) 2025 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0
#
# SPDX-License-Identifier: Apache-2.0
# *******************************************************************************
# Workflow configuration for S-CORE CI - Bazel Build & Test baselibs
# This workflow runs Bazel build and test when triggered by specific pull request events.
name: build latest mains
on:
  workflow_dispatch:
  pull_request:
  push:
  # schedule:
  #   - cron: '30 2 * * *'  # Every night at 02:30 UTC on main branch
jobs:
  integration_test:
    if: false # Temporarily disabled until we get things sorted out
    uses: ./.github/workflows/reusable_smoke-test.yml
    secrets: inherit
    with:
      repo_runner_labels: 'ubuntu-latest'
      module_name: 'reference_integration'
      target_branch: ${{ github.ref }}
